services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./server/db/postgres-init:/docker-entrypoint-initdb.d

  server:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DATABASE}
      JWT_SECRET: ${SUPABASE_JWT_SECRET}

  client:
    build: ./client
    ports:
      - "5173:5173"
    command: ["pnpm", "dev"]
    depends_on:
      - server

volumes:
  pg_data:
