CREATE TABLE IF NOT EXISTS me (
  id SERIAL PRIMARY KEY,
  nickname VARCHAR(12) UNIQUE NOT NULL,
  balance DECIMAL(10, 2) DEFAULT 1000.00,
  uuid CHAR(36) UNIQUE NOT NULL,
  refresh_token TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
